[package]
name = "analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
rdkafka = { workspace = true }
tokio = { workspace = true }
model = { workspace = true }
tempfile = { workspace = true }
url = { workspace = true }
